# -*- coding: utf-8 -*-
"""Workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waowFR2o2FxJK3RtU_J9kebPRGGpf4oe

Extract
"""

import pandas as pd
import sqlite3

#โหลดข้อมูลดิบ
df_raw = pd.read_csv('/content/raw_ecommerce_data.csv')

#ตรวจสอบโครงสร้างและค่า Null
df_raw.info()
display(df_raw.head())

print("===== Missing Value ก่อน =====")
print(df_raw.isnull().sum())

df_raw = df_raw.dropna()

print("===== Missing Value หลัง =====")
print(df_raw.isnull().sum())

"""2A : Transform (Dimension Table)"""

# สร้าง dim_customer
dim_customer = df_raw[['Customer_Name', 'Email']].drop_duplicates()

# สร้าง Surrogate Key (customer_id)
dim_customer = dim_customer.reset_index(drop=True)
dim_customer['customer_id'] = dim_customer.index + 1

# จัดเรียงคอลัมน์ให้ PK อยู่หน้าสุด
dim_customer = dim_customer[['customer_id', 'Customer_Name', 'Email']]
print("===== Customer Dimension =====")
display(dim_customer)
print("จำนวนลูกค้า =", len(dim_customer))

print("Duplicate =", df_raw.duplicated().sum())

df_raw = df_raw.drop_duplicates()

dim_product = df_raw[['Product']]

dim_product = dim_product.drop_duplicates()

dim_product = dim_product.reset_index(drop=True)

dim_product['product_id'] = dim_product.index + 1

dim_product = dim_product[
    ['product_id','Product']
]

display(dim_product)
print("จำนวนสินค้า =", len(dim_product))

"""2B : Transform"""

# นำ customer_id กลับไปใส่ใน fact table ผ่านการ Join
fact_sales = pd.merge(
    df_raw,
    dim_customer,
    on=['Customer_Name', 'Email'],
    how='left'
)
fact_sales = pd.merge(
    fact_sales,
    dim_product,
    on='Product',
    how='left'
)

# ลบคอลัมน์ Text ทิ้ง เหลือไว้เพียง Foreign Key
fact_sales = fact_sales.drop(columns=['Customer_Name', 'Email'])

# ทำซ้ำกระบวนการนี้กับ Product และ Time Dimensions

fact_sales = fact_sales.reset_index(drop=True)

fact_sales['transaction_id'] = fact_sales.index + 1

fact_sales = fact_sales[
    [
        'transaction_id',
        'customer_id',
        'product_id',
        'Amount'
    ]
]

display(fact_sales)
print("จำนวนรายการขาย =", len(fact_sales))

"""3A : Load"""

# 1. สร้าง Connection ไปที่ไฟล์ .db
conn = sqlite3.connect('warehouse.db')
cursor = conn.cursor()

# 2. สร้างตาราง Dimension พร้อมกำหนด Primary Key
cursor.execute('''
CREATE TABLE IF NOT EXISTS dim_customer (
    customer_id INTEGER PRIMARY KEY,
    Customer_Name TEXT,
    Email TEXT
)
''')

conn.commit()

#Product Table
cursor.execute("""

CREATE TABLE IF NOT EXISTS dim_product (

product_id INTEGER PRIMARY KEY,

Product TEXT

)

""")

conn.commit()

# เปิดใช้งานการตรวจสอบ Foreign Key ใน SQLite
cursor.execute("PRAGMA foreign_keys = ON;")

cursor.execute("""
CREATE TABLE IF NOT EXISTS fact_sales (
    transaction_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    product_id INTEGER,
    amount REAL,

    FOREIGN KEY (customer_id) REFERENCES dim_customer(customer_id),
    FOREIGN KEY (product_id) REFERENCES dim_product(product_id)
);
""")

conn.commit()

# โหลดข้อมูล Dimension
dim_customer.to_sql(
    'dim_customer',
    con=conn,
    if_exists='replace',
    index=False
)

dim_product.to_sql(
    'dim_product',
    con=conn,
    if_exists='replace',
    index=False
)
# โหลดข้อมูล Fact
fact_sales.to_sql(
    'fact_sales',
    con=conn,
    if_exists='replace',
    index=False
)

print("ETL Pipeline ran successfully!")

query = """

SELECT

    c.Customer_Name,

    SUM(f.Amount) AS Total_Spend

FROM fact_sales f

JOIN dim_customer c

ON f.customer_id = c.customer_id

GROUP BY c.Customer_Name

ORDER BY Total_Spend DESC

LIMIT 3;

"""

result = pd.read_sql_query(query, conn)

print("===== Top 3 Customer =====")
display(result)

conn.close()